// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc810.BullShirt.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc810.BullShirt.Robot;

/**
 *
 */
public class FireCannon extends Command {
	
	private boolean isRun = false;
	private long endTime;
	private boolean isStarted;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private int m_SafetyButton;
    private int m_CannonNumber;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public FireCannon(int SafetyButton, int CannonNumber) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_SafetyButton = SafetyButton;
        m_CannonNumber = CannonNumber;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.cannon);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if(isRun) return;
    	
    	if(!isStarted){
    		if(this.m_SafetyButton != -1){
    			if(!Robot.oi.getGamepad().getRawButton(m_SafetyButton)){
    				isRun = true;
    				return;
    			}
    		}

    		Robot.cannon.openValve(m_CannonNumber);
    		endTime = System.currentTimeMillis() + 250;
    		isStarted = true;
    	}
    	
    	else if(System.currentTimeMillis()>=endTime){
    		Robot.cannon.closeValve(m_CannonNumber);
    		isRun = true;
    	}
    
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isRun;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.cannon.closeValve(m_CannonNumber);
    	isRun = false;
    	isStarted = false;
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
